import applicationLoaded from './applicationLoaded';

import {
  createSnapshot,
  exportProject,
  projectExportDisplayed,
  projectExportNotDisplayed,
  createAssignment,
  updateAssignment,
  updateCourses,
  assignmentCreated,
  assignmentDisplayed,
  submitAssignment,
  assignmentSubmitted,
  assignmentSubmissionDisplayed,
  assignmentImported,
  assignmentImportError,
  assignmentNotFound,
  assignmentsLoaded,
} from './clients';

import {
  createProject,
  changeCurrentProject,
  toggleLibrary,
  hideComponent,
  unhideComponent,
  toggleComponent,
  updateProjectSource,
} from './projects';

import {
  focusLine,
  editorFocusedRequestedLine,
  dragRowDivider,
  dragColumnDivider,
  startDragColumnDivider,
  stopDragColumnDivider,
  notificationTriggered,
  userDismissedNotification,
  updateNotificationMetadata,
  popOutProject,
  toggleEditorTextSize,
  toggleTopBarMenu,
  closeTopBarMenu,
  assignmentSelectorOpened,
  openAssignmentSelector,
  assignmentSelectorClosed,
  courseSelected,
  dateSelected,
} from './ui';

import {
  addRuntimeError,
} from './errors';

import {
  logIn,
  logOut,
  userAuthenticated,
  userLoggedOut,
} from './user';

import {
  projectCompiled,
  projectCompilationFailed,
  refreshPreview,
} from './compiledProjects';

import {
  clearConsoleEntries,
  consoleErrorProduced,
  consoleLogProduced,
  consoleValueProduced,
  evaluateConsoleEntry,
} from './console';

export {
  clearConsoleEntries,
  consoleValueProduced,
  consoleErrorProduced,
  consoleLogProduced,
  createProject,
  createSnapshot,
  changeCurrentProject,
  updateProjectSource,
  toggleLibrary,
  userAuthenticated,
  userLoggedOut,
  addRuntimeError,
  hideComponent,
  unhideComponent,
  toggleComponent,
  focusLine,
  editorFocusedRequestedLine,
  dragRowDivider,
  dragColumnDivider,
  startDragColumnDivider,
  stopDragColumnDivider,
  notificationTriggered,
  userDismissedNotification,
  updateNotificationMetadata,
  exportProject,
  projectExportDisplayed,
  projectExportNotDisplayed,
  popOutProject,
  applicationLoaded,
  refreshPreview,
  toggleEditorTextSize,
  toggleTopBarMenu,
  closeTopBarMenu,
  logIn,
  logOut,
  evaluateConsoleEntry,
  projectCompiled,
  projectCompilationFailed,
  openAssignmentSelector,
  assignmentSelectorClosed,
  createAssignment,
  updateAssignment,
  updateCourses,
  assignmentSelectorOpened,
  assignmentCreated,
  assignmentDisplayed,
  courseSelected,
  dateSelected,
  submitAssignment,
  assignmentSubmitted,
  assignmentSubmissionDisplayed,
  assignmentImported,
  assignmentImportError,
  assignmentNotFound,
  assignmentsLoaded,
};
