#!/usr/bin/env node

/* eslint-env node */
/* eslint-disable import/no-commonjs */
/* eslint-disable import/no-nodejs-modules */
/* eslint-disable no-console */

const process = require('process');
const fs = require('fs');

const pify = require('pify');

async function checkEslintReactVersion() {
  const eslintrc = JSON.parse(
    await pify(fs.readFile)(`${__dirname}/../.eslintrc`),
  );
  const reactPackage = JSON.parse(
    await pify(fs.readFile)(require.resolve('react/package.json')),
  );
  if (eslintrc.settings.react.version !== reactPackage.version) {
    console.error('.eslintrc settings.react.version is not the version of react that is installed');
    process.exit(1);
  }
}

checkEslintReactVersion();
