#!/usr/bin/env node
/* eslint-disable import/no-commonjs, import/unambiguous */
/* eslint-env node */

const fs = require('fs');

const path = require('path');

const output = {};

['html', 'css', 'javascript'].forEach(language => {
  const dir = `./src/validations/__test__/acceptance/${language}`;

  output[language] = [];

  fs.readdirSync(dir).forEach(file => {
    output[language].push(
      fs.readFileSync(path.join(dir, file), {encoding: 'utf8'}),
    );
  });
});

fs.writeFile(
  './src/validations/acceptance.json',
  JSON.stringify(output, null, 2),
);
