#!/usr/bin/env bash

# Build your development environment. Running this on an already-built
# environment will update to the latest dependencies.


NODE_VERSION=10.16.0
YARN_VERSION=1.17.3
NODEENV_VERSION=1.3.3

export OSX=$(uname | grep -i '^darwin')

if [ -z "$(which python)" ] || [ -z "$(python --version | grep 'Python \(2\.7\|3\)')" ]
then
    echo "You need Python 2.7+ installed in order to run this script."
    if [  -z "$OSX" ]
    then
        if [ -z "$(which brew)" ]
        then
            cat <<MESSAGE

First, install Homebrew from
https://www.python.org/downloads/mac-osx/
MESSAGE
        fi
        cat <<MESSAGE

To install Python, run:

    $ brew install python
MESSAGE
    fi
    exit
fi

set -ex

NODEENV_TMPDIR=$(mktemp -d)
NODEENV_PACKAGE_DIR=$NODEENV_TMPDIR/nodeenv-$NODEENV_VERSION
curl --silent --location https://github.com/ekalinin/nodeenv/archive/$NODEENV_VERSION.tar.gz | tar --directory=$NODEENV_TMPDIR -xzf -

NODEENV_DIR=nodeenv
if [ -d $NODEENV_DIR ] && [ "$($NODEENV_DIR/bin/node --version)" != "v$NODE_VERSION" ]
then
    rm -r $NODEENV_DIR
fi

if [ ! -d $NODEENV_DIR ];
then
    python $NODEENV_PACKAGE_DIR/nodeenv.py --node=$NODE_VERSION nodeenv
fi

. $NODEENV_DIR/bin/activate

npm install --quiet --global yarn@$YARN_VERSION

yarn install --frozen-lockfile --non-interactive --no-progress --silent

if [ ! -e .vscode ]
then
    ln -sv --no-target-directory contrib/vscode .vscode
    if ! grep --quiet --no-messages .vscode .git/info/exclude
    then
        mkdir --parents .git/info
        echo .vscode >> .git/info/exclude
    fi
fi

set +x

cat <<MESSAGE

================================================================================

Your development environment is ready! To run your development server, type:

  tools/yarn start

To run tests in watch mode type:

  tools/yarn run autotest.jest

or

  tools/yarn run autotest.karma
MESSAGE
