#!/bin/bash

# Start a shell with the nodeenv loaded

if [ -d nodeenv ]
then
    bash --rcfile <(echo '. ~/.bashrc; . nodeenv/bin/activate') -i "$@"
else
    echo "You don’t seem to have a nodeenv installed, so falling back to normal shell. Run tools/setup to create a nodeenv."
    bash "$@"
fi
