#!/bin/sh

# Runs both test suites in watch mode

set -ex
case "$1" in
    "jest")
        docker-compose run --rm app yarn run autotest.jest
        ;;
    "karma")
        docker-compose run --rm --publish=9876:9876 --publish=9333:9333 app yarn run autotest.karma
        ;;
    *)
        docker-compose run --rm --publish=9876:9876 --publish=9333:9333 app yarn run $task
        ;;
esac
